package com.star.reward.infrastructure.persistence.dao.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class RewardTaskInstanceDOExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table reward_task_instance
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table reward_task_instance
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table reward_task_instance
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table reward_task_instance
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    protected Integer offset;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table reward_task_instance
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    protected Integer rows;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward_task_instance
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public RewardTaskInstanceDOExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward_task_instance
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward_task_instance
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward_task_instance
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward_task_instance
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward_task_instance
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward_task_instance
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward_task_instance
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward_task_instance
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward_task_instance
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward_task_instance
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
        rows = null;
        offset = null;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward_task_instance
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public void setOffset(Integer offset) {
        this.offset = offset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward_task_instance
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public Integer getOffset() {
        return this.offset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward_task_instance
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public void setRows(Integer rows) {
        this.rows = rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward_task_instance
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public Integer getRows() {
        return this.rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward_task_instance
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public RewardTaskInstanceDOExample limit(Integer rows) {
        this.rows = rows;
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward_task_instance
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public RewardTaskInstanceDOExample limit(Integer offset, Integer rows) {
        this.offset = offset;
        this.rows = rows;
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward_task_instance
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public RewardTaskInstanceDOExample page(Integer page, Integer pageSize) {
        this.offset = (page - 1) * pageSize;
        this.rows = pageSize;
        return this;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table reward_task_instance
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNull() {
            addCriterion("description is null");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNotNull() {
            addCriterion("description is not null");
            return (Criteria) this;
        }

        public Criteria andDescriptionEqualTo(String value) {
            addCriterion("description =", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotEqualTo(String value) {
            addCriterion("description <>", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThan(String value) {
            addCriterion("description >", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("description >=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThan(String value) {
            addCriterion("description <", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThanOrEqualTo(String value) {
            addCriterion("description <=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLike(String value) {
            addCriterion("description like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotLike(String value) {
            addCriterion("description not like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionIn(List<String> values) {
            addCriterion("description in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotIn(List<String> values) {
            addCriterion("description not in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionBetween(String value1, String value2) {
            addCriterion("description between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotBetween(String value1, String value2) {
            addCriterion("description not between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andMinUnitPointIsNull() {
            addCriterion("min_unit_point is null");
            return (Criteria) this;
        }

        public Criteria andMinUnitPointIsNotNull() {
            addCriterion("min_unit_point is not null");
            return (Criteria) this;
        }

        public Criteria andMinUnitPointEqualTo(Integer value) {
            addCriterion("min_unit_point =", value, "minUnitPoint");
            return (Criteria) this;
        }

        public Criteria andMinUnitPointNotEqualTo(Integer value) {
            addCriterion("min_unit_point <>", value, "minUnitPoint");
            return (Criteria) this;
        }

        public Criteria andMinUnitPointGreaterThan(Integer value) {
            addCriterion("min_unit_point >", value, "minUnitPoint");
            return (Criteria) this;
        }

        public Criteria andMinUnitPointGreaterThanOrEqualTo(Integer value) {
            addCriterion("min_unit_point >=", value, "minUnitPoint");
            return (Criteria) this;
        }

        public Criteria andMinUnitPointLessThan(Integer value) {
            addCriterion("min_unit_point <", value, "minUnitPoint");
            return (Criteria) this;
        }

        public Criteria andMinUnitPointLessThanOrEqualTo(Integer value) {
            addCriterion("min_unit_point <=", value, "minUnitPoint");
            return (Criteria) this;
        }

        public Criteria andMinUnitPointIn(List<Integer> values) {
            addCriterion("min_unit_point in", values, "minUnitPoint");
            return (Criteria) this;
        }

        public Criteria andMinUnitPointNotIn(List<Integer> values) {
            addCriterion("min_unit_point not in", values, "minUnitPoint");
            return (Criteria) this;
        }

        public Criteria andMinUnitPointBetween(Integer value1, Integer value2) {
            addCriterion("min_unit_point between", value1, value2, "minUnitPoint");
            return (Criteria) this;
        }

        public Criteria andMinUnitPointNotBetween(Integer value1, Integer value2) {
            addCriterion("min_unit_point not between", value1, value2, "minUnitPoint");
            return (Criteria) this;
        }

        public Criteria andMinUnitIsNull() {
            addCriterion("min_unit is null");
            return (Criteria) this;
        }

        public Criteria andMinUnitIsNotNull() {
            addCriterion("min_unit is not null");
            return (Criteria) this;
        }

        public Criteria andMinUnitEqualTo(String value) {
            addCriterion("min_unit =", value, "minUnit");
            return (Criteria) this;
        }

        public Criteria andMinUnitNotEqualTo(String value) {
            addCriterion("min_unit <>", value, "minUnit");
            return (Criteria) this;
        }

        public Criteria andMinUnitGreaterThan(String value) {
            addCriterion("min_unit >", value, "minUnit");
            return (Criteria) this;
        }

        public Criteria andMinUnitGreaterThanOrEqualTo(String value) {
            addCriterion("min_unit >=", value, "minUnit");
            return (Criteria) this;
        }

        public Criteria andMinUnitLessThan(String value) {
            addCriterion("min_unit <", value, "minUnit");
            return (Criteria) this;
        }

        public Criteria andMinUnitLessThanOrEqualTo(String value) {
            addCriterion("min_unit <=", value, "minUnit");
            return (Criteria) this;
        }

        public Criteria andMinUnitLike(String value) {
            addCriterion("min_unit like", value, "minUnit");
            return (Criteria) this;
        }

        public Criteria andMinUnitNotLike(String value) {
            addCriterion("min_unit not like", value, "minUnit");
            return (Criteria) this;
        }

        public Criteria andMinUnitIn(List<String> values) {
            addCriterion("min_unit in", values, "minUnit");
            return (Criteria) this;
        }

        public Criteria andMinUnitNotIn(List<String> values) {
            addCriterion("min_unit not in", values, "minUnit");
            return (Criteria) this;
        }

        public Criteria andMinUnitBetween(String value1, String value2) {
            addCriterion("min_unit between", value1, value2, "minUnit");
            return (Criteria) this;
        }

        public Criteria andMinUnitNotBetween(String value1, String value2) {
            addCriterion("min_unit not between", value1, value2, "minUnit");
            return (Criteria) this;
        }

        public Criteria andPublishByIsNull() {
            addCriterion("publish_by is null");
            return (Criteria) this;
        }

        public Criteria andPublishByIsNotNull() {
            addCriterion("publish_by is not null");
            return (Criteria) this;
        }

        public Criteria andPublishByEqualTo(String value) {
            addCriterion("publish_by =", value, "publishBy");
            return (Criteria) this;
        }

        public Criteria andPublishByNotEqualTo(String value) {
            addCriterion("publish_by <>", value, "publishBy");
            return (Criteria) this;
        }

        public Criteria andPublishByGreaterThan(String value) {
            addCriterion("publish_by >", value, "publishBy");
            return (Criteria) this;
        }

        public Criteria andPublishByGreaterThanOrEqualTo(String value) {
            addCriterion("publish_by >=", value, "publishBy");
            return (Criteria) this;
        }

        public Criteria andPublishByLessThan(String value) {
            addCriterion("publish_by <", value, "publishBy");
            return (Criteria) this;
        }

        public Criteria andPublishByLessThanOrEqualTo(String value) {
            addCriterion("publish_by <=", value, "publishBy");
            return (Criteria) this;
        }

        public Criteria andPublishByLike(String value) {
            addCriterion("publish_by like", value, "publishBy");
            return (Criteria) this;
        }

        public Criteria andPublishByNotLike(String value) {
            addCriterion("publish_by not like", value, "publishBy");
            return (Criteria) this;
        }

        public Criteria andPublishByIn(List<String> values) {
            addCriterion("publish_by in", values, "publishBy");
            return (Criteria) this;
        }

        public Criteria andPublishByNotIn(List<String> values) {
            addCriterion("publish_by not in", values, "publishBy");
            return (Criteria) this;
        }

        public Criteria andPublishByBetween(String value1, String value2) {
            addCriterion("publish_by between", value1, value2, "publishBy");
            return (Criteria) this;
        }

        public Criteria andPublishByNotBetween(String value1, String value2) {
            addCriterion("publish_by not between", value1, value2, "publishBy");
            return (Criteria) this;
        }

        public Criteria andPublishByIdIsNull() {
            addCriterion("publish_by_id is null");
            return (Criteria) this;
        }

        public Criteria andPublishByIdIsNotNull() {
            addCriterion("publish_by_id is not null");
            return (Criteria) this;
        }

        public Criteria andPublishByIdEqualTo(Long value) {
            addCriterion("publish_by_id =", value, "publishById");
            return (Criteria) this;
        }

        public Criteria andPublishByIdNotEqualTo(Long value) {
            addCriterion("publish_by_id <>", value, "publishById");
            return (Criteria) this;
        }

        public Criteria andPublishByIdGreaterThan(Long value) {
            addCriterion("publish_by_id >", value, "publishById");
            return (Criteria) this;
        }

        public Criteria andPublishByIdGreaterThanOrEqualTo(Long value) {
            addCriterion("publish_by_id >=", value, "publishById");
            return (Criteria) this;
        }

        public Criteria andPublishByIdLessThan(Long value) {
            addCriterion("publish_by_id <", value, "publishById");
            return (Criteria) this;
        }

        public Criteria andPublishByIdLessThanOrEqualTo(Long value) {
            addCriterion("publish_by_id <=", value, "publishById");
            return (Criteria) this;
        }

        public Criteria andPublishByIdIn(List<Long> values) {
            addCriterion("publish_by_id in", values, "publishById");
            return (Criteria) this;
        }

        public Criteria andPublishByIdNotIn(List<Long> values) {
            addCriterion("publish_by_id not in", values, "publishById");
            return (Criteria) this;
        }

        public Criteria andPublishByIdBetween(Long value1, Long value2) {
            addCriterion("publish_by_id between", value1, value2, "publishById");
            return (Criteria) this;
        }

        public Criteria andPublishByIdNotBetween(Long value1, Long value2) {
            addCriterion("publish_by_id not between", value1, value2, "publishById");
            return (Criteria) this;
        }

        public Criteria andStartTimeIsNull() {
            addCriterion("start_time is null");
            return (Criteria) this;
        }

        public Criteria andStartTimeIsNotNull() {
            addCriterion("start_time is not null");
            return (Criteria) this;
        }

        public Criteria andStartTimeEqualTo(Date value) {
            addCriterion("start_time =", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeNotEqualTo(Date value) {
            addCriterion("start_time <>", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeGreaterThan(Date value) {
            addCriterion("start_time >", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("start_time >=", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeLessThan(Date value) {
            addCriterion("start_time <", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeLessThanOrEqualTo(Date value) {
            addCriterion("start_time <=", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeIn(List<Date> values) {
            addCriterion("start_time in", values, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeNotIn(List<Date> values) {
            addCriterion("start_time not in", values, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeBetween(Date value1, Date value2) {
            addCriterion("start_time between", value1, value2, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeNotBetween(Date value1, Date value2) {
            addCriterion("start_time not between", value1, value2, "startTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeIsNull() {
            addCriterion("end_time is null");
            return (Criteria) this;
        }

        public Criteria andEndTimeIsNotNull() {
            addCriterion("end_time is not null");
            return (Criteria) this;
        }

        public Criteria andEndTimeEqualTo(Date value) {
            addCriterion("end_time =", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotEqualTo(Date value) {
            addCriterion("end_time <>", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeGreaterThan(Date value) {
            addCriterion("end_time >", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("end_time >=", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeLessThan(Date value) {
            addCriterion("end_time <", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeLessThanOrEqualTo(Date value) {
            addCriterion("end_time <=", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeIn(List<Date> values) {
            addCriterion("end_time in", values, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotIn(List<Date> values) {
            addCriterion("end_time not in", values, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeBetween(Date value1, Date value2) {
            addCriterion("end_time between", value1, value2, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotBetween(Date value1, Date value2) {
            addCriterion("end_time not between", value1, value2, "endTime");
            return (Criteria) this;
        }

        public Criteria andInstanceStateIsNull() {
            addCriterion("instance_state is null");
            return (Criteria) this;
        }

        public Criteria andInstanceStateIsNotNull() {
            addCriterion("instance_state is not null");
            return (Criteria) this;
        }

        public Criteria andInstanceStateEqualTo(String value) {
            addCriterion("instance_state =", value, "instanceState");
            return (Criteria) this;
        }

        public Criteria andInstanceStateNotEqualTo(String value) {
            addCriterion("instance_state <>", value, "instanceState");
            return (Criteria) this;
        }

        public Criteria andInstanceStateGreaterThan(String value) {
            addCriterion("instance_state >", value, "instanceState");
            return (Criteria) this;
        }

        public Criteria andInstanceStateGreaterThanOrEqualTo(String value) {
            addCriterion("instance_state >=", value, "instanceState");
            return (Criteria) this;
        }

        public Criteria andInstanceStateLessThan(String value) {
            addCriterion("instance_state <", value, "instanceState");
            return (Criteria) this;
        }

        public Criteria andInstanceStateLessThanOrEqualTo(String value) {
            addCriterion("instance_state <=", value, "instanceState");
            return (Criteria) this;
        }

        public Criteria andInstanceStateLike(String value) {
            addCriterion("instance_state like", value, "instanceState");
            return (Criteria) this;
        }

        public Criteria andInstanceStateNotLike(String value) {
            addCriterion("instance_state not like", value, "instanceState");
            return (Criteria) this;
        }

        public Criteria andInstanceStateIn(List<String> values) {
            addCriterion("instance_state in", values, "instanceState");
            return (Criteria) this;
        }

        public Criteria andInstanceStateNotIn(List<String> values) {
            addCriterion("instance_state not in", values, "instanceState");
            return (Criteria) this;
        }

        public Criteria andInstanceStateBetween(String value1, String value2) {
            addCriterion("instance_state between", value1, value2, "instanceState");
            return (Criteria) this;
        }

        public Criteria andInstanceStateNotBetween(String value1, String value2) {
            addCriterion("instance_state not between", value1, value2, "instanceState");
            return (Criteria) this;
        }

        public Criteria andExecuteByIsNull() {
            addCriterion("execute_by is null");
            return (Criteria) this;
        }

        public Criteria andExecuteByIsNotNull() {
            addCriterion("execute_by is not null");
            return (Criteria) this;
        }

        public Criteria andExecuteByEqualTo(String value) {
            addCriterion("execute_by =", value, "executeBy");
            return (Criteria) this;
        }

        public Criteria andExecuteByNotEqualTo(String value) {
            addCriterion("execute_by <>", value, "executeBy");
            return (Criteria) this;
        }

        public Criteria andExecuteByGreaterThan(String value) {
            addCriterion("execute_by >", value, "executeBy");
            return (Criteria) this;
        }

        public Criteria andExecuteByGreaterThanOrEqualTo(String value) {
            addCriterion("execute_by >=", value, "executeBy");
            return (Criteria) this;
        }

        public Criteria andExecuteByLessThan(String value) {
            addCriterion("execute_by <", value, "executeBy");
            return (Criteria) this;
        }

        public Criteria andExecuteByLessThanOrEqualTo(String value) {
            addCriterion("execute_by <=", value, "executeBy");
            return (Criteria) this;
        }

        public Criteria andExecuteByLike(String value) {
            addCriterion("execute_by like", value, "executeBy");
            return (Criteria) this;
        }

        public Criteria andExecuteByNotLike(String value) {
            addCriterion("execute_by not like", value, "executeBy");
            return (Criteria) this;
        }

        public Criteria andExecuteByIn(List<String> values) {
            addCriterion("execute_by in", values, "executeBy");
            return (Criteria) this;
        }

        public Criteria andExecuteByNotIn(List<String> values) {
            addCriterion("execute_by not in", values, "executeBy");
            return (Criteria) this;
        }

        public Criteria andExecuteByBetween(String value1, String value2) {
            addCriterion("execute_by between", value1, value2, "executeBy");
            return (Criteria) this;
        }

        public Criteria andExecuteByNotBetween(String value1, String value2) {
            addCriterion("execute_by not between", value1, value2, "executeBy");
            return (Criteria) this;
        }

        public Criteria andExecuteByIdIsNull() {
            addCriterion("execute_by_id is null");
            return (Criteria) this;
        }

        public Criteria andExecuteByIdIsNotNull() {
            addCriterion("execute_by_id is not null");
            return (Criteria) this;
        }

        public Criteria andExecuteByIdEqualTo(Long value) {
            addCriterion("execute_by_id =", value, "executeById");
            return (Criteria) this;
        }

        public Criteria andExecuteByIdNotEqualTo(Long value) {
            addCriterion("execute_by_id <>", value, "executeById");
            return (Criteria) this;
        }

        public Criteria andExecuteByIdGreaterThan(Long value) {
            addCriterion("execute_by_id >", value, "executeById");
            return (Criteria) this;
        }

        public Criteria andExecuteByIdGreaterThanOrEqualTo(Long value) {
            addCriterion("execute_by_id >=", value, "executeById");
            return (Criteria) this;
        }

        public Criteria andExecuteByIdLessThan(Long value) {
            addCriterion("execute_by_id <", value, "executeById");
            return (Criteria) this;
        }

        public Criteria andExecuteByIdLessThanOrEqualTo(Long value) {
            addCriterion("execute_by_id <=", value, "executeById");
            return (Criteria) this;
        }

        public Criteria andExecuteByIdIn(List<Long> values) {
            addCriterion("execute_by_id in", values, "executeById");
            return (Criteria) this;
        }

        public Criteria andExecuteByIdNotIn(List<Long> values) {
            addCriterion("execute_by_id not in", values, "executeById");
            return (Criteria) this;
        }

        public Criteria andExecuteByIdBetween(Long value1, Long value2) {
            addCriterion("execute_by_id between", value1, value2, "executeById");
            return (Criteria) this;
        }

        public Criteria andExecuteByIdNotBetween(Long value1, Long value2) {
            addCriterion("execute_by_id not between", value1, value2, "executeById");
            return (Criteria) this;
        }

        public Criteria andTemplateNoIsNull() {
            addCriterion("template_no is null");
            return (Criteria) this;
        }

        public Criteria andTemplateNoIsNotNull() {
            addCriterion("template_no is not null");
            return (Criteria) this;
        }

        public Criteria andTemplateNoEqualTo(String value) {
            addCriterion("template_no =", value, "templateNo");
            return (Criteria) this;
        }

        public Criteria andTemplateNoNotEqualTo(String value) {
            addCriterion("template_no <>", value, "templateNo");
            return (Criteria) this;
        }

        public Criteria andTemplateNoGreaterThan(String value) {
            addCriterion("template_no >", value, "templateNo");
            return (Criteria) this;
        }

        public Criteria andTemplateNoGreaterThanOrEqualTo(String value) {
            addCriterion("template_no >=", value, "templateNo");
            return (Criteria) this;
        }

        public Criteria andTemplateNoLessThan(String value) {
            addCriterion("template_no <", value, "templateNo");
            return (Criteria) this;
        }

        public Criteria andTemplateNoLessThanOrEqualTo(String value) {
            addCriterion("template_no <=", value, "templateNo");
            return (Criteria) this;
        }

        public Criteria andTemplateNoLike(String value) {
            addCriterion("template_no like", value, "templateNo");
            return (Criteria) this;
        }

        public Criteria andTemplateNoNotLike(String value) {
            addCriterion("template_no not like", value, "templateNo");
            return (Criteria) this;
        }

        public Criteria andTemplateNoIn(List<String> values) {
            addCriterion("template_no in", values, "templateNo");
            return (Criteria) this;
        }

        public Criteria andTemplateNoNotIn(List<String> values) {
            addCriterion("template_no not in", values, "templateNo");
            return (Criteria) this;
        }

        public Criteria andTemplateNoBetween(String value1, String value2) {
            addCriterion("template_no between", value1, value2, "templateNo");
            return (Criteria) this;
        }

        public Criteria andTemplateNoNotBetween(String value1, String value2) {
            addCriterion("template_no not between", value1, value2, "templateNo");
            return (Criteria) this;
        }

        public Criteria andInstanceNoIsNull() {
            addCriterion("instance_no is null");
            return (Criteria) this;
        }

        public Criteria andInstanceNoIsNotNull() {
            addCriterion("instance_no is not null");
            return (Criteria) this;
        }

        public Criteria andInstanceNoEqualTo(String value) {
            addCriterion("instance_no =", value, "instanceNo");
            return (Criteria) this;
        }

        public Criteria andInstanceNoNotEqualTo(String value) {
            addCriterion("instance_no <>", value, "instanceNo");
            return (Criteria) this;
        }

        public Criteria andInstanceNoGreaterThan(String value) {
            addCriterion("instance_no >", value, "instanceNo");
            return (Criteria) this;
        }

        public Criteria andInstanceNoGreaterThanOrEqualTo(String value) {
            addCriterion("instance_no >=", value, "instanceNo");
            return (Criteria) this;
        }

        public Criteria andInstanceNoLessThan(String value) {
            addCriterion("instance_no <", value, "instanceNo");
            return (Criteria) this;
        }

        public Criteria andInstanceNoLessThanOrEqualTo(String value) {
            addCriterion("instance_no <=", value, "instanceNo");
            return (Criteria) this;
        }

        public Criteria andInstanceNoLike(String value) {
            addCriterion("instance_no like", value, "instanceNo");
            return (Criteria) this;
        }

        public Criteria andInstanceNoNotLike(String value) {
            addCriterion("instance_no not like", value, "instanceNo");
            return (Criteria) this;
        }

        public Criteria andInstanceNoIn(List<String> values) {
            addCriterion("instance_no in", values, "instanceNo");
            return (Criteria) this;
        }

        public Criteria andInstanceNoNotIn(List<String> values) {
            addCriterion("instance_no not in", values, "instanceNo");
            return (Criteria) this;
        }

        public Criteria andInstanceNoBetween(String value1, String value2) {
            addCriterion("instance_no between", value1, value2, "instanceNo");
            return (Criteria) this;
        }

        public Criteria andInstanceNoNotBetween(String value1, String value2) {
            addCriterion("instance_no not between", value1, value2, "instanceNo");
            return (Criteria) this;
        }

        public Criteria andIsPresetIsNull() {
            addCriterion("is_preset is null");
            return (Criteria) this;
        }

        public Criteria andIsPresetIsNotNull() {
            addCriterion("is_preset is not null");
            return (Criteria) this;
        }

        public Criteria andIsPresetEqualTo(Byte value) {
            addCriterion("is_preset =", value, "isPreset");
            return (Criteria) this;
        }

        public Criteria andIsPresetNotEqualTo(Byte value) {
            addCriterion("is_preset <>", value, "isPreset");
            return (Criteria) this;
        }

        public Criteria andIsPresetGreaterThan(Byte value) {
            addCriterion("is_preset >", value, "isPreset");
            return (Criteria) this;
        }

        public Criteria andIsPresetGreaterThanOrEqualTo(Byte value) {
            addCriterion("is_preset >=", value, "isPreset");
            return (Criteria) this;
        }

        public Criteria andIsPresetLessThan(Byte value) {
            addCriterion("is_preset <", value, "isPreset");
            return (Criteria) this;
        }

        public Criteria andIsPresetLessThanOrEqualTo(Byte value) {
            addCriterion("is_preset <=", value, "isPreset");
            return (Criteria) this;
        }

        public Criteria andIsPresetIn(List<Byte> values) {
            addCriterion("is_preset in", values, "isPreset");
            return (Criteria) this;
        }

        public Criteria andIsPresetNotIn(List<Byte> values) {
            addCriterion("is_preset not in", values, "isPreset");
            return (Criteria) this;
        }

        public Criteria andIsPresetBetween(Byte value1, Byte value2) {
            addCriterion("is_preset between", value1, value2, "isPreset");
            return (Criteria) this;
        }

        public Criteria andIsPresetNotBetween(Byte value1, Byte value2) {
            addCriterion("is_preset not between", value1, value2, "isPreset");
            return (Criteria) this;
        }

        public Criteria andIsDeletedIsNull() {
            addCriterion("is_deleted is null");
            return (Criteria) this;
        }

        public Criteria andIsDeletedIsNotNull() {
            addCriterion("is_deleted is not null");
            return (Criteria) this;
        }

        public Criteria andIsDeletedEqualTo(Byte value) {
            addCriterion("is_deleted =", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedNotEqualTo(Byte value) {
            addCriterion("is_deleted <>", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedGreaterThan(Byte value) {
            addCriterion("is_deleted >", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedGreaterThanOrEqualTo(Byte value) {
            addCriterion("is_deleted >=", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedLessThan(Byte value) {
            addCriterion("is_deleted <", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedLessThanOrEqualTo(Byte value) {
            addCriterion("is_deleted <=", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedIn(List<Byte> values) {
            addCriterion("is_deleted in", values, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedNotIn(List<Byte> values) {
            addCriterion("is_deleted not in", values, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedBetween(Byte value1, Byte value2) {
            addCriterion("is_deleted between", value1, value2, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedNotBetween(Byte value1, Byte value2) {
            addCriterion("is_deleted not between", value1, value2, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andCreateByIsNull() {
            addCriterion("create_by is null");
            return (Criteria) this;
        }

        public Criteria andCreateByIsNotNull() {
            addCriterion("create_by is not null");
            return (Criteria) this;
        }

        public Criteria andCreateByEqualTo(String value) {
            addCriterion("create_by =", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByNotEqualTo(String value) {
            addCriterion("create_by <>", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByGreaterThan(String value) {
            addCriterion("create_by >", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByGreaterThanOrEqualTo(String value) {
            addCriterion("create_by >=", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByLessThan(String value) {
            addCriterion("create_by <", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByLessThanOrEqualTo(String value) {
            addCriterion("create_by <=", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByLike(String value) {
            addCriterion("create_by like", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByNotLike(String value) {
            addCriterion("create_by not like", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByIn(List<String> values) {
            addCriterion("create_by in", values, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByNotIn(List<String> values) {
            addCriterion("create_by not in", values, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByBetween(String value1, String value2) {
            addCriterion("create_by between", value1, value2, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByNotBetween(String value1, String value2) {
            addCriterion("create_by not between", value1, value2, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByIdIsNull() {
            addCriterion("create_by_id is null");
            return (Criteria) this;
        }

        public Criteria andCreateByIdIsNotNull() {
            addCriterion("create_by_id is not null");
            return (Criteria) this;
        }

        public Criteria andCreateByIdEqualTo(Long value) {
            addCriterion("create_by_id =", value, "createById");
            return (Criteria) this;
        }

        public Criteria andCreateByIdNotEqualTo(Long value) {
            addCriterion("create_by_id <>", value, "createById");
            return (Criteria) this;
        }

        public Criteria andCreateByIdGreaterThan(Long value) {
            addCriterion("create_by_id >", value, "createById");
            return (Criteria) this;
        }

        public Criteria andCreateByIdGreaterThanOrEqualTo(Long value) {
            addCriterion("create_by_id >=", value, "createById");
            return (Criteria) this;
        }

        public Criteria andCreateByIdLessThan(Long value) {
            addCriterion("create_by_id <", value, "createById");
            return (Criteria) this;
        }

        public Criteria andCreateByIdLessThanOrEqualTo(Long value) {
            addCriterion("create_by_id <=", value, "createById");
            return (Criteria) this;
        }

        public Criteria andCreateByIdIn(List<Long> values) {
            addCriterion("create_by_id in", values, "createById");
            return (Criteria) this;
        }

        public Criteria andCreateByIdNotIn(List<Long> values) {
            addCriterion("create_by_id not in", values, "createById");
            return (Criteria) this;
        }

        public Criteria andCreateByIdBetween(Long value1, Long value2) {
            addCriterion("create_by_id between", value1, value2, "createById");
            return (Criteria) this;
        }

        public Criteria andCreateByIdNotBetween(Long value1, Long value2) {
            addCriterion("create_by_id not between", value1, value2, "createById");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateByIsNull() {
            addCriterion("update_by is null");
            return (Criteria) this;
        }

        public Criteria andUpdateByIsNotNull() {
            addCriterion("update_by is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateByEqualTo(String value) {
            addCriterion("update_by =", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByNotEqualTo(String value) {
            addCriterion("update_by <>", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByGreaterThan(String value) {
            addCriterion("update_by >", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByGreaterThanOrEqualTo(String value) {
            addCriterion("update_by >=", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByLessThan(String value) {
            addCriterion("update_by <", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByLessThanOrEqualTo(String value) {
            addCriterion("update_by <=", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByLike(String value) {
            addCriterion("update_by like", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByNotLike(String value) {
            addCriterion("update_by not like", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByIn(List<String> values) {
            addCriterion("update_by in", values, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByNotIn(List<String> values) {
            addCriterion("update_by not in", values, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByBetween(String value1, String value2) {
            addCriterion("update_by between", value1, value2, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByNotBetween(String value1, String value2) {
            addCriterion("update_by not between", value1, value2, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByIdIsNull() {
            addCriterion("update_by_id is null");
            return (Criteria) this;
        }

        public Criteria andUpdateByIdIsNotNull() {
            addCriterion("update_by_id is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateByIdEqualTo(Long value) {
            addCriterion("update_by_id =", value, "updateById");
            return (Criteria) this;
        }

        public Criteria andUpdateByIdNotEqualTo(Long value) {
            addCriterion("update_by_id <>", value, "updateById");
            return (Criteria) this;
        }

        public Criteria andUpdateByIdGreaterThan(Long value) {
            addCriterion("update_by_id >", value, "updateById");
            return (Criteria) this;
        }

        public Criteria andUpdateByIdGreaterThanOrEqualTo(Long value) {
            addCriterion("update_by_id >=", value, "updateById");
            return (Criteria) this;
        }

        public Criteria andUpdateByIdLessThan(Long value) {
            addCriterion("update_by_id <", value, "updateById");
            return (Criteria) this;
        }

        public Criteria andUpdateByIdLessThanOrEqualTo(Long value) {
            addCriterion("update_by_id <=", value, "updateById");
            return (Criteria) this;
        }

        public Criteria andUpdateByIdIn(List<Long> values) {
            addCriterion("update_by_id in", values, "updateById");
            return (Criteria) this;
        }

        public Criteria andUpdateByIdNotIn(List<Long> values) {
            addCriterion("update_by_id not in", values, "updateById");
            return (Criteria) this;
        }

        public Criteria andUpdateByIdBetween(Long value1, Long value2) {
            addCriterion("update_by_id between", value1, value2, "updateById");
            return (Criteria) this;
        }

        public Criteria andUpdateByIdNotBetween(Long value1, Long value2) {
            addCriterion("update_by_id not between", value1, value2, "updateById");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("remark is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("remark is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("remark =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("remark <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("remark >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("remark >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("remark <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("remark <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("remark like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("remark not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("remark in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("remark not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("remark between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("remark not between", value1, value2, "remark");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table reward_task_instance
     *
     * @mbg.generated do_not_delete_during_merge Sat Feb 07 19:27:58 CST 2026
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table reward_task_instance
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}