package com.star.reward.infrastructure.persistence.dao.entity;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table reward_purchase_record
 */
public class RewardPurchaseRecordDO implements Serializable {
    /**
     * Database Column Remarks:
     *   自增主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reward_purchase_record.id
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   商品名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reward_purchase_record.name
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    private String name;

    /**
     * Database Column Remarks:
     *   商品描述
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reward_purchase_record.description
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    private String description;

    /**
     * Database Column Remarks:
     *   单价
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reward_purchase_record.price
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    private BigDecimal price;

    /**
     * Database Column Remarks:
     *   最小购买数量
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reward_purchase_record.min_quantity
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    private BigDecimal minQuantity;

    /**
     * Database Column Remarks:
     *   单位 g min
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reward_purchase_record.min_unit
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    private String minUnit;

    /**
     * Database Column Remarks:
     *   发布人账号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reward_purchase_record.publish_by
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    private String publishBy;

    /**
     * Database Column Remarks:
     *   发布人ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reward_purchase_record.publish_by_id
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    private Long publishById;

    /**
     * Database Column Remarks:
     *   购买份数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reward_purchase_record.purchase_quantity
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    private Integer purchaseQuantity;

    /**
     * Database Column Remarks:
     *   购买人账号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reward_purchase_record.purchase_by
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    private String purchaseBy;

    /**
     * Database Column Remarks:
     *   购买人ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reward_purchase_record.purchase_by_id
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    private Long purchaseById;

    /**
     * Database Column Remarks:
     *   商品编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reward_purchase_record.product_no
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    private String productNo;

    /**
     * Database Column Remarks:
     *   购买记录编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reward_purchase_record.purchase_no
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    private String purchaseNo;

    /**
     * Database Column Remarks:
     *   是否为预设。0-否 1-是
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reward_purchase_record.is_preset
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    private Byte isPreset;

    /**
     * Database Column Remarks:
     *   是否删除。0-否 1-是
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reward_purchase_record.is_deleted
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    private Byte isDeleted;

    /**
     * Database Column Remarks:
     *   创建人账号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reward_purchase_record.create_by
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    private String createBy;

    /**
     * Database Column Remarks:
     *   创建人ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reward_purchase_record.create_by_id
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    private Long createById;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reward_purchase_record.create_time
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   更新人账号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reward_purchase_record.update_by
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    private String updateBy;

    /**
     * Database Column Remarks:
     *   更新人ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reward_purchase_record.update_by_id
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    private Long updateById;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reward_purchase_record.update_time
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    private Date updateTime;

    /**
     * Database Column Remarks:
     *   备注
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reward_purchase_record.remark
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    private String remark;

    /**
     * Database Column Remarks:
     *   扩展字段
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reward_purchase_record.attributes
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    private String attributes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table reward_purchase_record
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reward_purchase_record.id
     *
     * @return the value of reward_purchase_record.id
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reward_purchase_record.id
     *
     * @param id the value for reward_purchase_record.id
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reward_purchase_record.name
     *
     * @return the value of reward_purchase_record.name
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reward_purchase_record.name
     *
     * @param name the value for reward_purchase_record.name
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reward_purchase_record.description
     *
     * @return the value of reward_purchase_record.description
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reward_purchase_record.description
     *
     * @param description the value for reward_purchase_record.description
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reward_purchase_record.price
     *
     * @return the value of reward_purchase_record.price
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reward_purchase_record.price
     *
     * @param price the value for reward_purchase_record.price
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reward_purchase_record.min_quantity
     *
     * @return the value of reward_purchase_record.min_quantity
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public BigDecimal getMinQuantity() {
        return minQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reward_purchase_record.min_quantity
     *
     * @param minQuantity the value for reward_purchase_record.min_quantity
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public void setMinQuantity(BigDecimal minQuantity) {
        this.minQuantity = minQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reward_purchase_record.min_unit
     *
     * @return the value of reward_purchase_record.min_unit
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public String getMinUnit() {
        return minUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reward_purchase_record.min_unit
     *
     * @param minUnit the value for reward_purchase_record.min_unit
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public void setMinUnit(String minUnit) {
        this.minUnit = minUnit == null ? null : minUnit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reward_purchase_record.publish_by
     *
     * @return the value of reward_purchase_record.publish_by
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public String getPublishBy() {
        return publishBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reward_purchase_record.publish_by
     *
     * @param publishBy the value for reward_purchase_record.publish_by
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public void setPublishBy(String publishBy) {
        this.publishBy = publishBy == null ? null : publishBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reward_purchase_record.publish_by_id
     *
     * @return the value of reward_purchase_record.publish_by_id
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public Long getPublishById() {
        return publishById;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reward_purchase_record.publish_by_id
     *
     * @param publishById the value for reward_purchase_record.publish_by_id
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public void setPublishById(Long publishById) {
        this.publishById = publishById;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reward_purchase_record.purchase_quantity
     *
     * @return the value of reward_purchase_record.purchase_quantity
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public Integer getPurchaseQuantity() {
        return purchaseQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reward_purchase_record.purchase_quantity
     *
     * @param purchaseQuantity the value for reward_purchase_record.purchase_quantity
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public void setPurchaseQuantity(Integer purchaseQuantity) {
        this.purchaseQuantity = purchaseQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reward_purchase_record.purchase_by
     *
     * @return the value of reward_purchase_record.purchase_by
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public String getPurchaseBy() {
        return purchaseBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reward_purchase_record.purchase_by
     *
     * @param purchaseBy the value for reward_purchase_record.purchase_by
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public void setPurchaseBy(String purchaseBy) {
        this.purchaseBy = purchaseBy == null ? null : purchaseBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reward_purchase_record.purchase_by_id
     *
     * @return the value of reward_purchase_record.purchase_by_id
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public Long getPurchaseById() {
        return purchaseById;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reward_purchase_record.purchase_by_id
     *
     * @param purchaseById the value for reward_purchase_record.purchase_by_id
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public void setPurchaseById(Long purchaseById) {
        this.purchaseById = purchaseById;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reward_purchase_record.product_no
     *
     * @return the value of reward_purchase_record.product_no
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public String getProductNo() {
        return productNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reward_purchase_record.product_no
     *
     * @param productNo the value for reward_purchase_record.product_no
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public void setProductNo(String productNo) {
        this.productNo = productNo == null ? null : productNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reward_purchase_record.purchase_no
     *
     * @return the value of reward_purchase_record.purchase_no
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public String getPurchaseNo() {
        return purchaseNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reward_purchase_record.purchase_no
     *
     * @param purchaseNo the value for reward_purchase_record.purchase_no
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public void setPurchaseNo(String purchaseNo) {
        this.purchaseNo = purchaseNo == null ? null : purchaseNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reward_purchase_record.is_preset
     *
     * @return the value of reward_purchase_record.is_preset
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public Byte getIsPreset() {
        return isPreset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reward_purchase_record.is_preset
     *
     * @param isPreset the value for reward_purchase_record.is_preset
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public void setIsPreset(Byte isPreset) {
        this.isPreset = isPreset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reward_purchase_record.is_deleted
     *
     * @return the value of reward_purchase_record.is_deleted
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public Byte getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reward_purchase_record.is_deleted
     *
     * @param isDeleted the value for reward_purchase_record.is_deleted
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public void setIsDeleted(Byte isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reward_purchase_record.create_by
     *
     * @return the value of reward_purchase_record.create_by
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reward_purchase_record.create_by
     *
     * @param createBy the value for reward_purchase_record.create_by
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reward_purchase_record.create_by_id
     *
     * @return the value of reward_purchase_record.create_by_id
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public Long getCreateById() {
        return createById;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reward_purchase_record.create_by_id
     *
     * @param createById the value for reward_purchase_record.create_by_id
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public void setCreateById(Long createById) {
        this.createById = createById;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reward_purchase_record.create_time
     *
     * @return the value of reward_purchase_record.create_time
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reward_purchase_record.create_time
     *
     * @param createTime the value for reward_purchase_record.create_time
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reward_purchase_record.update_by
     *
     * @return the value of reward_purchase_record.update_by
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reward_purchase_record.update_by
     *
     * @param updateBy the value for reward_purchase_record.update_by
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reward_purchase_record.update_by_id
     *
     * @return the value of reward_purchase_record.update_by_id
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public Long getUpdateById() {
        return updateById;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reward_purchase_record.update_by_id
     *
     * @param updateById the value for reward_purchase_record.update_by_id
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public void setUpdateById(Long updateById) {
        this.updateById = updateById;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reward_purchase_record.update_time
     *
     * @return the value of reward_purchase_record.update_time
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reward_purchase_record.update_time
     *
     * @param updateTime the value for reward_purchase_record.update_time
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reward_purchase_record.remark
     *
     * @return the value of reward_purchase_record.remark
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reward_purchase_record.remark
     *
     * @param remark the value for reward_purchase_record.remark
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reward_purchase_record.attributes
     *
     * @return the value of reward_purchase_record.attributes
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public String getAttributes() {
        return attributes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reward_purchase_record.attributes
     *
     * @param attributes the value for reward_purchase_record.attributes
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public void setAttributes(String attributes) {
        this.attributes = attributes == null ? null : attributes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward_purchase_record
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", description=").append(description);
        sb.append(", price=").append(price);
        sb.append(", minQuantity=").append(minQuantity);
        sb.append(", minUnit=").append(minUnit);
        sb.append(", publishBy=").append(publishBy);
        sb.append(", publishById=").append(publishById);
        sb.append(", purchaseQuantity=").append(purchaseQuantity);
        sb.append(", purchaseBy=").append(purchaseBy);
        sb.append(", purchaseById=").append(purchaseById);
        sb.append(", productNo=").append(productNo);
        sb.append(", purchaseNo=").append(purchaseNo);
        sb.append(", isPreset=").append(isPreset);
        sb.append(", isDeleted=").append(isDeleted);
        sb.append(", createBy=").append(createBy);
        sb.append(", createById=").append(createById);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateBy=").append(updateBy);
        sb.append(", updateById=").append(updateById);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", remark=").append(remark);
        sb.append(", attributes=").append(attributes);
        sb.append("]");
        return sb.toString();
    }
}