package com.star.reward.infrastructure.persistence.dao.entity;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table reward_user_inventory
 */
public class RewardUserInventoryDO implements Serializable {
    /**
     * Database Column Remarks:
     *   自增主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reward_user_inventory.id
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   库存类型。POINT-积分 PRODUCT-商品
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reward_user_inventory.inventory_type
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    private String inventoryType;

    /**
     * Database Column Remarks:
     *   库存名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reward_user_inventory.name
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    private String name;

    /**
     * Database Column Remarks:
     *   库存描述
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reward_user_inventory.description
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    private String description;

    /**
     * Database Column Remarks:
     *   库存数量
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reward_user_inventory.quantity
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    private BigDecimal quantity;

    /**
     * Database Column Remarks:
     *   单位 g min
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reward_user_inventory.unit
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    private String unit;

    /**
     * Database Column Remarks:
     *   发布人账号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reward_user_inventory.publish_by
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    private String publishBy;

    /**
     * Database Column Remarks:
     *   发布人ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reward_user_inventory.publish_by_id
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    private Long publishById;

    /**
     * Database Column Remarks:
     *   所属人账号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reward_user_inventory.belong_to
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    private String belongTo;

    /**
     * Database Column Remarks:
     *   所属人ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reward_user_inventory.belong_to_id
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    private Long belongToId;

    /**
     * Database Column Remarks:
     *   库存编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reward_user_inventory.inventory_no
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    private String inventoryNo;

    /**
     * Database Column Remarks:
     *   是否删除。0-否 1-是
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reward_user_inventory.is_deleted
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    private Byte isDeleted;

    /**
     * Database Column Remarks:
     *   创建人账号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reward_user_inventory.create_by
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    private String createBy;

    /**
     * Database Column Remarks:
     *   创建人ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reward_user_inventory.create_by_id
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    private Long createById;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reward_user_inventory.create_time
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   更新人账号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reward_user_inventory.update_by
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    private String updateBy;

    /**
     * Database Column Remarks:
     *   更新人ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reward_user_inventory.update_by_id
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    private Long updateById;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reward_user_inventory.update_time
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    private Date updateTime;

    /**
     * Database Column Remarks:
     *   备注
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reward_user_inventory.remark
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    private String remark;

    /**
     * Database Column Remarks:
     *   扩展字段
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reward_user_inventory.attributes
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    private String attributes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table reward_user_inventory
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reward_user_inventory.id
     *
     * @return the value of reward_user_inventory.id
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reward_user_inventory.id
     *
     * @param id the value for reward_user_inventory.id
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reward_user_inventory.inventory_type
     *
     * @return the value of reward_user_inventory.inventory_type
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public String getInventoryType() {
        return inventoryType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reward_user_inventory.inventory_type
     *
     * @param inventoryType the value for reward_user_inventory.inventory_type
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public void setInventoryType(String inventoryType) {
        this.inventoryType = inventoryType == null ? null : inventoryType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reward_user_inventory.name
     *
     * @return the value of reward_user_inventory.name
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reward_user_inventory.name
     *
     * @param name the value for reward_user_inventory.name
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reward_user_inventory.description
     *
     * @return the value of reward_user_inventory.description
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reward_user_inventory.description
     *
     * @param description the value for reward_user_inventory.description
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reward_user_inventory.quantity
     *
     * @return the value of reward_user_inventory.quantity
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public BigDecimal getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reward_user_inventory.quantity
     *
     * @param quantity the value for reward_user_inventory.quantity
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public void setQuantity(BigDecimal quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reward_user_inventory.unit
     *
     * @return the value of reward_user_inventory.unit
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reward_user_inventory.unit
     *
     * @param unit the value for reward_user_inventory.unit
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public void setUnit(String unit) {
        this.unit = unit == null ? null : unit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reward_user_inventory.publish_by
     *
     * @return the value of reward_user_inventory.publish_by
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public String getPublishBy() {
        return publishBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reward_user_inventory.publish_by
     *
     * @param publishBy the value for reward_user_inventory.publish_by
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public void setPublishBy(String publishBy) {
        this.publishBy = publishBy == null ? null : publishBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reward_user_inventory.publish_by_id
     *
     * @return the value of reward_user_inventory.publish_by_id
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public Long getPublishById() {
        return publishById;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reward_user_inventory.publish_by_id
     *
     * @param publishById the value for reward_user_inventory.publish_by_id
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public void setPublishById(Long publishById) {
        this.publishById = publishById;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reward_user_inventory.belong_to
     *
     * @return the value of reward_user_inventory.belong_to
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public String getBelongTo() {
        return belongTo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reward_user_inventory.belong_to
     *
     * @param belongTo the value for reward_user_inventory.belong_to
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public void setBelongTo(String belongTo) {
        this.belongTo = belongTo == null ? null : belongTo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reward_user_inventory.belong_to_id
     *
     * @return the value of reward_user_inventory.belong_to_id
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public Long getBelongToId() {
        return belongToId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reward_user_inventory.belong_to_id
     *
     * @param belongToId the value for reward_user_inventory.belong_to_id
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public void setBelongToId(Long belongToId) {
        this.belongToId = belongToId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reward_user_inventory.inventory_no
     *
     * @return the value of reward_user_inventory.inventory_no
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public String getInventoryNo() {
        return inventoryNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reward_user_inventory.inventory_no
     *
     * @param inventoryNo the value for reward_user_inventory.inventory_no
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public void setInventoryNo(String inventoryNo) {
        this.inventoryNo = inventoryNo == null ? null : inventoryNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reward_user_inventory.is_deleted
     *
     * @return the value of reward_user_inventory.is_deleted
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public Byte getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reward_user_inventory.is_deleted
     *
     * @param isDeleted the value for reward_user_inventory.is_deleted
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public void setIsDeleted(Byte isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reward_user_inventory.create_by
     *
     * @return the value of reward_user_inventory.create_by
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reward_user_inventory.create_by
     *
     * @param createBy the value for reward_user_inventory.create_by
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reward_user_inventory.create_by_id
     *
     * @return the value of reward_user_inventory.create_by_id
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public Long getCreateById() {
        return createById;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reward_user_inventory.create_by_id
     *
     * @param createById the value for reward_user_inventory.create_by_id
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public void setCreateById(Long createById) {
        this.createById = createById;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reward_user_inventory.create_time
     *
     * @return the value of reward_user_inventory.create_time
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reward_user_inventory.create_time
     *
     * @param createTime the value for reward_user_inventory.create_time
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reward_user_inventory.update_by
     *
     * @return the value of reward_user_inventory.update_by
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reward_user_inventory.update_by
     *
     * @param updateBy the value for reward_user_inventory.update_by
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reward_user_inventory.update_by_id
     *
     * @return the value of reward_user_inventory.update_by_id
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public Long getUpdateById() {
        return updateById;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reward_user_inventory.update_by_id
     *
     * @param updateById the value for reward_user_inventory.update_by_id
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public void setUpdateById(Long updateById) {
        this.updateById = updateById;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reward_user_inventory.update_time
     *
     * @return the value of reward_user_inventory.update_time
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reward_user_inventory.update_time
     *
     * @param updateTime the value for reward_user_inventory.update_time
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reward_user_inventory.remark
     *
     * @return the value of reward_user_inventory.remark
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reward_user_inventory.remark
     *
     * @param remark the value for reward_user_inventory.remark
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reward_user_inventory.attributes
     *
     * @return the value of reward_user_inventory.attributes
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public String getAttributes() {
        return attributes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reward_user_inventory.attributes
     *
     * @param attributes the value for reward_user_inventory.attributes
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public void setAttributes(String attributes) {
        this.attributes = attributes == null ? null : attributes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward_user_inventory
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", inventoryType=").append(inventoryType);
        sb.append(", name=").append(name);
        sb.append(", description=").append(description);
        sb.append(", quantity=").append(quantity);
        sb.append(", unit=").append(unit);
        sb.append(", publishBy=").append(publishBy);
        sb.append(", publishById=").append(publishById);
        sb.append(", belongTo=").append(belongTo);
        sb.append(", belongToId=").append(belongToId);
        sb.append(", inventoryNo=").append(inventoryNo);
        sb.append(", isDeleted=").append(isDeleted);
        sb.append(", createBy=").append(createBy);
        sb.append(", createById=").append(createById);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateBy=").append(updateBy);
        sb.append(", updateById=").append(updateById);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", remark=").append(remark);
        sb.append(", attributes=").append(attributes);
        sb.append("]");
        return sb.toString();
    }
}