package com.star.reward.infrastructure.persistence.dao.entity;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table reward_point_record
 */
public class RewardPointRecordDO implements Serializable {
    /**
     * Database Column Remarks:
     *   自增主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reward_point_record.id
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   记录编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reward_point_record.record_no
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    private String recordNo;

    /**
     * Database Column Remarks:
     *   类型。EARN-获取 SPEND-消耗
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reward_point_record.point_type
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    private String pointType;

    /**
     * Database Column Remarks:
     *   积分数量
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reward_point_record.amount
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    private BigDecimal amount;

    /**
     * Database Column Remarks:
     *   所属人账号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reward_point_record.belong_to
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    private String belongTo;

    /**
     * Database Column Remarks:
     *   所属人ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reward_point_record.belong_to_id
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    private Long belongToId;

    /**
     * Database Column Remarks:
     *   关联业务ID（任务实例编号/购买记录编号）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reward_point_record.related_id
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    private String relatedId;

    /**
     * Database Column Remarks:
     *   描述
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reward_point_record.description
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    private String description;

    /**
     * Database Column Remarks:
     *   创建人账号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reward_point_record.create_by
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    private String createBy;

    /**
     * Database Column Remarks:
     *   创建人ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reward_point_record.create_by_id
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    private Long createById;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reward_point_record.create_time
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table reward_point_record
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reward_point_record.id
     *
     * @return the value of reward_point_record.id
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reward_point_record.id
     *
     * @param id the value for reward_point_record.id
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reward_point_record.record_no
     *
     * @return the value of reward_point_record.record_no
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public String getRecordNo() {
        return recordNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reward_point_record.record_no
     *
     * @param recordNo the value for reward_point_record.record_no
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public void setRecordNo(String recordNo) {
        this.recordNo = recordNo == null ? null : recordNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reward_point_record.point_type
     *
     * @return the value of reward_point_record.point_type
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public String getPointType() {
        return pointType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reward_point_record.point_type
     *
     * @param pointType the value for reward_point_record.point_type
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public void setPointType(String pointType) {
        this.pointType = pointType == null ? null : pointType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reward_point_record.amount
     *
     * @return the value of reward_point_record.amount
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reward_point_record.amount
     *
     * @param amount the value for reward_point_record.amount
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reward_point_record.belong_to
     *
     * @return the value of reward_point_record.belong_to
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public String getBelongTo() {
        return belongTo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reward_point_record.belong_to
     *
     * @param belongTo the value for reward_point_record.belong_to
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public void setBelongTo(String belongTo) {
        this.belongTo = belongTo == null ? null : belongTo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reward_point_record.belong_to_id
     *
     * @return the value of reward_point_record.belong_to_id
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public Long getBelongToId() {
        return belongToId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reward_point_record.belong_to_id
     *
     * @param belongToId the value for reward_point_record.belong_to_id
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public void setBelongToId(Long belongToId) {
        this.belongToId = belongToId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reward_point_record.related_id
     *
     * @return the value of reward_point_record.related_id
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public String getRelatedId() {
        return relatedId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reward_point_record.related_id
     *
     * @param relatedId the value for reward_point_record.related_id
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public void setRelatedId(String relatedId) {
        this.relatedId = relatedId == null ? null : relatedId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reward_point_record.description
     *
     * @return the value of reward_point_record.description
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reward_point_record.description
     *
     * @param description the value for reward_point_record.description
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reward_point_record.create_by
     *
     * @return the value of reward_point_record.create_by
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reward_point_record.create_by
     *
     * @param createBy the value for reward_point_record.create_by
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reward_point_record.create_by_id
     *
     * @return the value of reward_point_record.create_by_id
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public Long getCreateById() {
        return createById;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reward_point_record.create_by_id
     *
     * @param createById the value for reward_point_record.create_by_id
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public void setCreateById(Long createById) {
        this.createById = createById;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reward_point_record.create_time
     *
     * @return the value of reward_point_record.create_time
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reward_point_record.create_time
     *
     * @param createTime the value for reward_point_record.create_time
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward_point_record
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", recordNo=").append(recordNo);
        sb.append(", pointType=").append(pointType);
        sb.append(", amount=").append(amount);
        sb.append(", belongTo=").append(belongTo);
        sb.append(", belongToId=").append(belongToId);
        sb.append(", relatedId=").append(relatedId);
        sb.append(", description=").append(description);
        sb.append(", createBy=").append(createBy);
        sb.append(", createById=").append(createById);
        sb.append(", createTime=").append(createTime);
        sb.append("]");
        return sb.toString();
    }
}