package com.star.reward.infrastructure.persistence.dao.entity;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table reward_task_instance
 */
public class RewardTaskInstanceDO implements Serializable {
    /**
     * Database Column Remarks:
     *   自增主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reward_task_instance.id
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   任务名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reward_task_instance.name
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    private String name;

    /**
     * Database Column Remarks:
     *   任务描述
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reward_task_instance.description
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    private String description;

    /**
     * Database Column Remarks:
     *   1最小单位积分
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reward_task_instance.min_unit_point
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    private Integer minUnitPoint;

    /**
     * Database Column Remarks:
     *   最小单位 MIN-分钟
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reward_task_instance.min_unit
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    private String minUnit;

    /**
     * Database Column Remarks:
     *   发布人账号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reward_task_instance.publish_by
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    private String publishBy;

    /**
     * Database Column Remarks:
     *   发布人ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reward_task_instance.publish_by_id
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    private Long publishById;

    /**
     * Database Column Remarks:
     *   实例开始时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reward_task_instance.start_time
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    private Date startTime;

    /**
     * Database Column Remarks:
     *   实例结束时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reward_task_instance.end_time
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    private Date endTime;

    /**
     * Database Column Remarks:
     *   实例状态 RUNNING-执行中 PAUSED-暂停 END-结束
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reward_task_instance.instance_state
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    private String instanceState;

    /**
     * Database Column Remarks:
     *   执行人账号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reward_task_instance.execute_by
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    private String executeBy;

    /**
     * Database Column Remarks:
     *   执行人ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reward_task_instance.execute_by_id
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    private Long executeById;

    /**
     * Database Column Remarks:
     *   模板编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reward_task_instance.template_no
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    private String templateNo;

    /**
     * Database Column Remarks:
     *   实例编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reward_task_instance.instance_no
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    private String instanceNo;

    /**
     * Database Column Remarks:
     *   是否为预设任务。0-否 1-是
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reward_task_instance.is_preset
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    private Byte isPreset;

    /**
     * Database Column Remarks:
     *   是否删除。0-否 1-是
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reward_task_instance.is_deleted
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    private Byte isDeleted;

    /**
     * Database Column Remarks:
     *   创建人账号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reward_task_instance.create_by
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    private String createBy;

    /**
     * Database Column Remarks:
     *   创建人ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reward_task_instance.create_by_id
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    private Long createById;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reward_task_instance.create_time
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   更新人账号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reward_task_instance.update_by
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    private String updateBy;

    /**
     * Database Column Remarks:
     *   更新人ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reward_task_instance.update_by_id
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    private Long updateById;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reward_task_instance.update_time
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    private Date updateTime;

    /**
     * Database Column Remarks:
     *   备注
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reward_task_instance.remark
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    private String remark;

    /**
     * Database Column Remarks:
     *   扩展字段
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reward_task_instance.attributes
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    private String attributes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table reward_task_instance
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reward_task_instance.id
     *
     * @return the value of reward_task_instance.id
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reward_task_instance.id
     *
     * @param id the value for reward_task_instance.id
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reward_task_instance.name
     *
     * @return the value of reward_task_instance.name
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reward_task_instance.name
     *
     * @param name the value for reward_task_instance.name
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reward_task_instance.description
     *
     * @return the value of reward_task_instance.description
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reward_task_instance.description
     *
     * @param description the value for reward_task_instance.description
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reward_task_instance.min_unit_point
     *
     * @return the value of reward_task_instance.min_unit_point
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public Integer getMinUnitPoint() {
        return minUnitPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reward_task_instance.min_unit_point
     *
     * @param minUnitPoint the value for reward_task_instance.min_unit_point
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public void setMinUnitPoint(Integer minUnitPoint) {
        this.minUnitPoint = minUnitPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reward_task_instance.min_unit
     *
     * @return the value of reward_task_instance.min_unit
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public String getMinUnit() {
        return minUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reward_task_instance.min_unit
     *
     * @param minUnit the value for reward_task_instance.min_unit
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public void setMinUnit(String minUnit) {
        this.minUnit = minUnit == null ? null : minUnit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reward_task_instance.publish_by
     *
     * @return the value of reward_task_instance.publish_by
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public String getPublishBy() {
        return publishBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reward_task_instance.publish_by
     *
     * @param publishBy the value for reward_task_instance.publish_by
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public void setPublishBy(String publishBy) {
        this.publishBy = publishBy == null ? null : publishBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reward_task_instance.publish_by_id
     *
     * @return the value of reward_task_instance.publish_by_id
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public Long getPublishById() {
        return publishById;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reward_task_instance.publish_by_id
     *
     * @param publishById the value for reward_task_instance.publish_by_id
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public void setPublishById(Long publishById) {
        this.publishById = publishById;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reward_task_instance.start_time
     *
     * @return the value of reward_task_instance.start_time
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reward_task_instance.start_time
     *
     * @param startTime the value for reward_task_instance.start_time
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reward_task_instance.end_time
     *
     * @return the value of reward_task_instance.end_time
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reward_task_instance.end_time
     *
     * @param endTime the value for reward_task_instance.end_time
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reward_task_instance.instance_state
     *
     * @return the value of reward_task_instance.instance_state
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public String getInstanceState() {
        return instanceState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reward_task_instance.instance_state
     *
     * @param instanceState the value for reward_task_instance.instance_state
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public void setInstanceState(String instanceState) {
        this.instanceState = instanceState == null ? null : instanceState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reward_task_instance.execute_by
     *
     * @return the value of reward_task_instance.execute_by
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public String getExecuteBy() {
        return executeBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reward_task_instance.execute_by
     *
     * @param executeBy the value for reward_task_instance.execute_by
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public void setExecuteBy(String executeBy) {
        this.executeBy = executeBy == null ? null : executeBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reward_task_instance.execute_by_id
     *
     * @return the value of reward_task_instance.execute_by_id
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public Long getExecuteById() {
        return executeById;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reward_task_instance.execute_by_id
     *
     * @param executeById the value for reward_task_instance.execute_by_id
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public void setExecuteById(Long executeById) {
        this.executeById = executeById;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reward_task_instance.template_no
     *
     * @return the value of reward_task_instance.template_no
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public String getTemplateNo() {
        return templateNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reward_task_instance.template_no
     *
     * @param templateNo the value for reward_task_instance.template_no
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public void setTemplateNo(String templateNo) {
        this.templateNo = templateNo == null ? null : templateNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reward_task_instance.instance_no
     *
     * @return the value of reward_task_instance.instance_no
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public String getInstanceNo() {
        return instanceNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reward_task_instance.instance_no
     *
     * @param instanceNo the value for reward_task_instance.instance_no
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public void setInstanceNo(String instanceNo) {
        this.instanceNo = instanceNo == null ? null : instanceNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reward_task_instance.is_preset
     *
     * @return the value of reward_task_instance.is_preset
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public Byte getIsPreset() {
        return isPreset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reward_task_instance.is_preset
     *
     * @param isPreset the value for reward_task_instance.is_preset
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public void setIsPreset(Byte isPreset) {
        this.isPreset = isPreset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reward_task_instance.is_deleted
     *
     * @return the value of reward_task_instance.is_deleted
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public Byte getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reward_task_instance.is_deleted
     *
     * @param isDeleted the value for reward_task_instance.is_deleted
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public void setIsDeleted(Byte isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reward_task_instance.create_by
     *
     * @return the value of reward_task_instance.create_by
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reward_task_instance.create_by
     *
     * @param createBy the value for reward_task_instance.create_by
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reward_task_instance.create_by_id
     *
     * @return the value of reward_task_instance.create_by_id
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public Long getCreateById() {
        return createById;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reward_task_instance.create_by_id
     *
     * @param createById the value for reward_task_instance.create_by_id
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public void setCreateById(Long createById) {
        this.createById = createById;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reward_task_instance.create_time
     *
     * @return the value of reward_task_instance.create_time
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reward_task_instance.create_time
     *
     * @param createTime the value for reward_task_instance.create_time
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reward_task_instance.update_by
     *
     * @return the value of reward_task_instance.update_by
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reward_task_instance.update_by
     *
     * @param updateBy the value for reward_task_instance.update_by
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reward_task_instance.update_by_id
     *
     * @return the value of reward_task_instance.update_by_id
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public Long getUpdateById() {
        return updateById;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reward_task_instance.update_by_id
     *
     * @param updateById the value for reward_task_instance.update_by_id
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public void setUpdateById(Long updateById) {
        this.updateById = updateById;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reward_task_instance.update_time
     *
     * @return the value of reward_task_instance.update_time
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reward_task_instance.update_time
     *
     * @param updateTime the value for reward_task_instance.update_time
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reward_task_instance.remark
     *
     * @return the value of reward_task_instance.remark
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reward_task_instance.remark
     *
     * @param remark the value for reward_task_instance.remark
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reward_task_instance.attributes
     *
     * @return the value of reward_task_instance.attributes
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public String getAttributes() {
        return attributes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reward_task_instance.attributes
     *
     * @param attributes the value for reward_task_instance.attributes
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    public void setAttributes(String attributes) {
        this.attributes = attributes == null ? null : attributes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward_task_instance
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", description=").append(description);
        sb.append(", minUnitPoint=").append(minUnitPoint);
        sb.append(", minUnit=").append(minUnit);
        sb.append(", publishBy=").append(publishBy);
        sb.append(", publishById=").append(publishById);
        sb.append(", startTime=").append(startTime);
        sb.append(", endTime=").append(endTime);
        sb.append(", instanceState=").append(instanceState);
        sb.append(", executeBy=").append(executeBy);
        sb.append(", executeById=").append(executeById);
        sb.append(", templateNo=").append(templateNo);
        sb.append(", instanceNo=").append(instanceNo);
        sb.append(", isPreset=").append(isPreset);
        sb.append(", isDeleted=").append(isDeleted);
        sb.append(", createBy=").append(createBy);
        sb.append(", createById=").append(createById);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateBy=").append(updateBy);
        sb.append(", updateById=").append(updateById);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", remark=").append(remark);
        sb.append(", attributes=").append(attributes);
        sb.append("]");
        return sb.toString();
    }
}