-- reward 表，原 V1__init_reward_tables.sql 重命名

-- 任务模板表
CREATE TABLE `reward_task_template` (
	`id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '自增主键',
	`name` varchar(32) NOT NULL COMMENT '任务名称',
	`description` varchar(500) NOT NULL COMMENT '任务描述',
	`min_unit_point` decimal(20,6) UNSIGNED NOT NULL DEFAULT 1 COMMENT '1最小单位积分',
	`min_unit` varchar(32) NOT NULL DEFAULT 'MIN' COMMENT '最小单位 MIN-分钟',
	`publish_by` varchar(32) NOT NULL COMMENT '发布人账号',
	`publish_by_id` bigint(20) UNSIGNED NOT NULL COMMENT '发布人ID',
	`template_no` varchar(32) NOT NULL COMMENT '模板编号',
	`is_preset` tinyint(4) UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否为预设任务。0-否 1-是',
	`is_deleted` tinyint(4) UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否删除。0-否 1-是',
	`create_by` varchar(32) NOT NULL COMMENT '创建人账号',
	`create_by_id` bigint(20) UNSIGNED NOT NULL COMMENT '创建人ID',
	`create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
	`update_by` varchar(32) NOT NULL COMMENT '更新人账号',
	`update_by_id` bigint(20) UNSIGNED NOT NULL COMMENT '更新人ID',
	`update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
	`remark` varchar(512) NULL COMMENT '备注',
	`attributes` json NULL COMMENT '扩展字段',
	PRIMARY KEY (`id`),
	UNIQUE KEY `udx_template_no` (`template_no`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='任务模板表';

-- 任务实例表
CREATE TABLE `reward_task_instance` (
	`id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '自增主键',
	`name` varchar(32) NOT NULL COMMENT '任务名称',
	`description` varchar(500) NOT NULL COMMENT '任务描述',
	`min_unit_point` int(11) UNSIGNED NOT NULL DEFAULT 1 COMMENT '1最小单位积分',
	`min_unit` varchar(32) NOT NULL DEFAULT 'MIN' COMMENT '最小单位 MIN-分钟',
	`publish_by` varchar(32) NOT NULL COMMENT '发布人账号',
	`publish_by_id` bigint(20) UNSIGNED NOT NULL COMMENT '发布人ID',
	`start_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '实例开始时间',
	`end_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '实例结束时间',
	`instance_state` varchar(32) NOT NULL COMMENT '实例状态 RUNNING-执行中 PAUSED-暂停 END-结束',
	`execute_by` varchar(32) NOT NULL COMMENT '执行人账号',
	`execute_by_id` bigint(20) UNSIGNED NOT NULL COMMENT '执行人ID',
	`template_no` varchar(32) NOT NULL COMMENT '模板编号',
	`instance_no` varchar(32) NOT NULL COMMENT '实例编号',
	`is_preset` tinyint(4) UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否为预设任务。0-否 1-是',
	`is_deleted` tinyint(4) UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否删除。0-否 1-是',
	`create_by` varchar(32) NOT NULL COMMENT '创建人账号',
	`create_by_id` bigint(20) UNSIGNED NOT NULL COMMENT '创建人ID',
	`create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
	`update_by` varchar(32) NOT NULL COMMENT '更新人账号',
	`update_by_id` bigint(20) UNSIGNED NOT NULL COMMENT '更新人ID',
	`update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
	`remark` varchar(512) NULL COMMENT '备注',
	`attributes` json NULL COMMENT '扩展字段',
	PRIMARY KEY (`id`),
	UNIQUE KEY `udx_instance_no` (`instance_no`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='任务实例表';

-- 商品表
CREATE TABLE `reward_product` (
	`id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '自增主键',
	`name` varchar(32) NOT NULL COMMENT '商品名称',
	`description` varchar(500) NOT NULL COMMENT '商品描述',
	`price` decimal(20,6) UNSIGNED NOT NULL COMMENT '单价',
	`min_quantity` decimal(20,6) UNSIGNED NOT NULL COMMENT '最小购买数量',
	`min_unit` varchar(20) NULL COMMENT '单位 g min',
	`publish_by` varchar(32) NOT NULL COMMENT '发布人账号',
	`publish_by_id` bigint(20) UNSIGNED NOT NULL COMMENT '发布人ID',
	`product_no` varchar(32) NOT NULL COMMENT '商品编号',
	`is_preset` tinyint(4) UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否为预设。0-否 1-是',
	`is_deleted` tinyint(4) UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否删除。0-否 1-是',
	`create_by` varchar(32) NOT NULL COMMENT '创建人账号',
	`create_by_id` bigint(20) UNSIGNED NOT NULL COMMENT '创建人ID',
	`create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
	`update_by` varchar(32) NOT NULL COMMENT '更新人账号',
	`update_by_id` bigint(20) UNSIGNED NOT NULL COMMENT '更新人ID',
	`update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
	`remark` varchar(512) NULL COMMENT '备注',
	`attributes` json NULL COMMENT '扩展字段',
	PRIMARY KEY (`id`),
	UNIQUE KEY `udx_product_no` (`product_no`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='商品表';

-- 用户库存表
CREATE TABLE `reward_user_inventory` (
	`id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '自增主键',
	`inventory_type` varchar(32) NOT NULL COMMENT '库存类型。POINT-积分 PRODUCT-商品',
	`name` varchar(32) NOT NULL COMMENT '库存名称',
	`description` varchar(500) NOT NULL COMMENT '库存描述',
	`quantity` decimal(20,6) UNSIGNED NOT NULL COMMENT '库存数量',
	`unit` varchar(20) NULL COMMENT '单位 g min',
	`publish_by` varchar(32) NOT NULL COMMENT '发布人账号',
	`publish_by_id` bigint(20) UNSIGNED NOT NULL COMMENT '发布人ID',
	`belong_to` varchar(32) NOT NULL COMMENT '所属人账号',
	`belong_to_id` bigint(20) UNSIGNED NOT NULL COMMENT '所属人ID',
	`inventory_no` varchar(32) NOT NULL COMMENT '库存编号',
	`is_deleted` tinyint(4) UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否删除。0-否 1-是',
	`create_by` varchar(32) NOT NULL COMMENT '创建人账号',
	`create_by_id` bigint(20) UNSIGNED NOT NULL COMMENT '创建人ID',
	`create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
	`update_by` varchar(32) NOT NULL COMMENT '更新人账号',
	`update_by_id` bigint(20) UNSIGNED NOT NULL COMMENT '更新人ID',
	`update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
	`remark` varchar(512) NULL COMMENT '备注',
	`attributes` json NULL COMMENT '扩展字段',
	PRIMARY KEY (`id`),
	UNIQUE KEY `udx_inventory_no` (`inventory_no`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='用户库存表';

-- 购买记录表
CREATE TABLE `reward_purchase_record` (
	`id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '自增主键',
	`name` varchar(32) NOT NULL COMMENT '商品名称',
	`description` varchar(500) NOT NULL COMMENT '商品描述',
	`price` decimal(20,6) UNSIGNED NOT NULL COMMENT '单价',
	`min_quantity` decimal(20,6) UNSIGNED NOT NULL COMMENT '最小购买数量',
	`min_unit` varchar(20) NULL COMMENT '单位 g min',
	`publish_by` varchar(32) NOT NULL COMMENT '发布人账号',
	`publish_by_id` bigint(20) UNSIGNED NOT NULL COMMENT '发布人ID',
	`purchase_quantity` int(11) UNSIGNED NOT NULL COMMENT '购买份数',
	`purchase_by` varchar(32) NOT NULL COMMENT '购买人账号',
	`purchase_by_id` bigint(20) UNSIGNED NOT NULL COMMENT '购买人ID',
	`product_no` varchar(32) NOT NULL COMMENT '商品编号',
	`purchase_no` varchar(32) NOT NULL COMMENT '购买记录编号',
	`is_preset` tinyint(4) UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否为预设。0-否 1-是',
	`is_deleted` tinyint(4) UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否删除。0-否 1-是',
	`create_by` varchar(32) NOT NULL COMMENT '创建人账号',
	`create_by_id` bigint(20) UNSIGNED NOT NULL COMMENT '创建人ID',
	`create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
	`update_by` varchar(32) NOT NULL COMMENT '更新人账号',
	`update_by_id` bigint(20) UNSIGNED NOT NULL COMMENT '更新人ID',
	`update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
	`remark` varchar(512) NULL COMMENT '备注',
	`attributes` json NULL COMMENT '扩展字段',
	PRIMARY KEY (`id`),
	UNIQUE KEY `udx_purchase_no` (`purchase_no`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='商品购买记录表';
