package com.star.reward.infrastructure.persistence.dao.mapper;

import com.star.reward.infrastructure.persistence.dao.entity.RewardUserInventoryDO;
import com.star.reward.infrastructure.persistence.dao.entity.RewardUserInventoryDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RewardUserInventoryDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward_user_inventory
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    long countByExample(RewardUserInventoryDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward_user_inventory
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    int deleteByExample(RewardUserInventoryDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward_user_inventory
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward_user_inventory
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    int insert(RewardUserInventoryDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward_user_inventory
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    int insertSelective(RewardUserInventoryDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward_user_inventory
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    List<RewardUserInventoryDO> selectByExampleWithBLOBs(RewardUserInventoryDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward_user_inventory
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    List<RewardUserInventoryDO> selectByExample(RewardUserInventoryDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward_user_inventory
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    RewardUserInventoryDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward_user_inventory
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    int updateByExampleSelective(@Param("record") RewardUserInventoryDO record, @Param("example") RewardUserInventoryDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward_user_inventory
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    int updateByExampleWithBLOBs(@Param("record") RewardUserInventoryDO record, @Param("example") RewardUserInventoryDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward_user_inventory
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    int updateByExample(@Param("record") RewardUserInventoryDO record, @Param("example") RewardUserInventoryDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward_user_inventory
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    int updateByPrimaryKeySelective(RewardUserInventoryDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward_user_inventory
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    int updateByPrimaryKeyWithBLOBs(RewardUserInventoryDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward_user_inventory
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    int updateByPrimaryKey(RewardUserInventoryDO record);
}