package com.star.reward.infrastructure.persistence.dao.mapper;

import com.star.reward.infrastructure.persistence.dao.entity.RewardTaskTemplateDO;
import com.star.reward.infrastructure.persistence.dao.entity.RewardTaskTemplateDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RewardTaskTemplateDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward_task_template
     *
     * @mbg.generated Mon Jan 26 16:13:28 CST 2026
     */
    long countByExample(RewardTaskTemplateDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward_task_template
     *
     * @mbg.generated Mon Jan 26 16:13:28 CST 2026
     */
    int deleteByExample(RewardTaskTemplateDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward_task_template
     *
     * @mbg.generated Mon Jan 26 16:13:28 CST 2026
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward_task_template
     *
     * @mbg.generated Mon Jan 26 16:13:28 CST 2026
     */
    int insert(RewardTaskTemplateDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward_task_template
     *
     * @mbg.generated Mon Jan 26 16:13:28 CST 2026
     */
    int insertSelective(RewardTaskTemplateDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward_task_template
     *
     * @mbg.generated Mon Jan 26 16:13:28 CST 2026
     */
    List<RewardTaskTemplateDO> selectByExampleWithBLOBs(RewardTaskTemplateDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward_task_template
     *
     * @mbg.generated Mon Jan 26 16:13:28 CST 2026
     */
    List<RewardTaskTemplateDO> selectByExample(RewardTaskTemplateDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward_task_template
     *
     * @mbg.generated Mon Jan 26 16:13:28 CST 2026
     */
    RewardTaskTemplateDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward_task_template
     *
     * @mbg.generated Mon Jan 26 16:13:28 CST 2026
     */
    int updateByExampleSelective(@Param("row") RewardTaskTemplateDO row, @Param("example") RewardTaskTemplateDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward_task_template
     *
     * @mbg.generated Mon Jan 26 16:13:28 CST 2026
     */
    int updateByExampleWithBLOBs(@Param("row") RewardTaskTemplateDO row, @Param("example") RewardTaskTemplateDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward_task_template
     *
     * @mbg.generated Mon Jan 26 16:13:28 CST 2026
     */
    int updateByExample(@Param("row") RewardTaskTemplateDO row, @Param("example") RewardTaskTemplateDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward_task_template
     *
     * @mbg.generated Mon Jan 26 16:13:28 CST 2026
     */
    int updateByPrimaryKeySelective(RewardTaskTemplateDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward_task_template
     *
     * @mbg.generated Mon Jan 26 16:13:28 CST 2026
     */
    int updateByPrimaryKeyWithBLOBs(RewardTaskTemplateDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward_task_template
     *
     * @mbg.generated Mon Jan 26 16:13:28 CST 2026
     */
    int updateByPrimaryKey(RewardTaskTemplateDO row);
}