package com.star.reward.infrastructure.persistence.dao.mapper;

import com.star.reward.infrastructure.persistence.dao.entity.RewardProductDO;
import com.star.reward.infrastructure.persistence.dao.entity.RewardProductDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RewardProductDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward_product
     *
     * @mbg.generated Mon Jan 26 16:13:28 CST 2026
     */
    long countByExample(RewardProductDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward_product
     *
     * @mbg.generated Mon Jan 26 16:13:28 CST 2026
     */
    int deleteByExample(RewardProductDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward_product
     *
     * @mbg.generated Mon Jan 26 16:13:28 CST 2026
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward_product
     *
     * @mbg.generated Mon Jan 26 16:13:28 CST 2026
     */
    int insert(RewardProductDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward_product
     *
     * @mbg.generated Mon Jan 26 16:13:28 CST 2026
     */
    int insertSelective(RewardProductDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward_product
     *
     * @mbg.generated Mon Jan 26 16:13:28 CST 2026
     */
    List<RewardProductDO> selectByExampleWithBLOBs(RewardProductDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward_product
     *
     * @mbg.generated Mon Jan 26 16:13:28 CST 2026
     */
    List<RewardProductDO> selectByExample(RewardProductDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward_product
     *
     * @mbg.generated Mon Jan 26 16:13:28 CST 2026
     */
    RewardProductDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward_product
     *
     * @mbg.generated Mon Jan 26 16:13:28 CST 2026
     */
    int updateByExampleSelective(@Param("row") RewardProductDO row, @Param("example") RewardProductDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward_product
     *
     * @mbg.generated Mon Jan 26 16:13:28 CST 2026
     */
    int updateByExampleWithBLOBs(@Param("row") RewardProductDO row, @Param("example") RewardProductDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward_product
     *
     * @mbg.generated Mon Jan 26 16:13:28 CST 2026
     */
    int updateByExample(@Param("row") RewardProductDO row, @Param("example") RewardProductDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward_product
     *
     * @mbg.generated Mon Jan 26 16:13:28 CST 2026
     */
    int updateByPrimaryKeySelective(RewardProductDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward_product
     *
     * @mbg.generated Mon Jan 26 16:13:28 CST 2026
     */
    int updateByPrimaryKeyWithBLOBs(RewardProductDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward_product
     *
     * @mbg.generated Mon Jan 26 16:13:28 CST 2026
     */
    int updateByPrimaryKey(RewardProductDO row);
}