package com.star.reward.infrastructure.persistence.dao.mapper;

import com.star.reward.infrastructure.persistence.dao.entity.RewardUserInventoryDO;
import com.star.reward.infrastructure.persistence.dao.entity.RewardUserInventoryDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RewardUserInventoryDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward_user_inventory
     *
     * @mbg.generated Mon Jan 26 16:13:28 CST 2026
     */
    long countByExample(RewardUserInventoryDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward_user_inventory
     *
     * @mbg.generated Mon Jan 26 16:13:28 CST 2026
     */
    int deleteByExample(RewardUserInventoryDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward_user_inventory
     *
     * @mbg.generated Mon Jan 26 16:13:28 CST 2026
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward_user_inventory
     *
     * @mbg.generated Mon Jan 26 16:13:28 CST 2026
     */
    int insert(RewardUserInventoryDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward_user_inventory
     *
     * @mbg.generated Mon Jan 26 16:13:28 CST 2026
     */
    int insertSelective(RewardUserInventoryDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward_user_inventory
     *
     * @mbg.generated Mon Jan 26 16:13:28 CST 2026
     */
    List<RewardUserInventoryDO> selectByExampleWithBLOBs(RewardUserInventoryDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward_user_inventory
     *
     * @mbg.generated Mon Jan 26 16:13:28 CST 2026
     */
    List<RewardUserInventoryDO> selectByExample(RewardUserInventoryDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward_user_inventory
     *
     * @mbg.generated Mon Jan 26 16:13:28 CST 2026
     */
    RewardUserInventoryDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward_user_inventory
     *
     * @mbg.generated Mon Jan 26 16:13:28 CST 2026
     */
    int updateByExampleSelective(@Param("row") RewardUserInventoryDO row, @Param("example") RewardUserInventoryDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward_user_inventory
     *
     * @mbg.generated Mon Jan 26 16:13:28 CST 2026
     */
    int updateByExampleWithBLOBs(@Param("row") RewardUserInventoryDO row, @Param("example") RewardUserInventoryDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward_user_inventory
     *
     * @mbg.generated Mon Jan 26 16:13:28 CST 2026
     */
    int updateByExample(@Param("row") RewardUserInventoryDO row, @Param("example") RewardUserInventoryDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward_user_inventory
     *
     * @mbg.generated Mon Jan 26 16:13:28 CST 2026
     */
    int updateByPrimaryKeySelective(RewardUserInventoryDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward_user_inventory
     *
     * @mbg.generated Mon Jan 26 16:13:28 CST 2026
     */
    int updateByPrimaryKeyWithBLOBs(RewardUserInventoryDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward_user_inventory
     *
     * @mbg.generated Mon Jan 26 16:13:28 CST 2026
     */
    int updateByPrimaryKey(RewardUserInventoryDO row);
}