package com.star.reward.infrastructure.persistence.dao.mapper;

import com.star.reward.infrastructure.persistence.dao.entity.RewardPointRecordDO;
import com.star.reward.infrastructure.persistence.dao.entity.RewardPointRecordDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RewardPointRecordDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward_point_record
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    long countByExample(RewardPointRecordDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward_point_record
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    int deleteByExample(RewardPointRecordDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward_point_record
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward_point_record
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    int insert(RewardPointRecordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward_point_record
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    int insertSelective(RewardPointRecordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward_point_record
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    List<RewardPointRecordDO> selectByExample(RewardPointRecordDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward_point_record
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    RewardPointRecordDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward_point_record
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    int updateByExampleSelective(@Param("record") RewardPointRecordDO record, @Param("example") RewardPointRecordDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward_point_record
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    int updateByExample(@Param("record") RewardPointRecordDO record, @Param("example") RewardPointRecordDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward_point_record
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    int updateByPrimaryKeySelective(RewardPointRecordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward_point_record
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    int updateByPrimaryKey(RewardPointRecordDO record);
}