package com.star.reward.infrastructure.persistence.dao.mapper;

import com.star.reward.infrastructure.persistence.dao.entity.RewardPurchaseRecordDO;
import com.star.reward.infrastructure.persistence.dao.entity.RewardPurchaseRecordDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RewardPurchaseRecordDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward_purchase_record
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    long countByExample(RewardPurchaseRecordDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward_purchase_record
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    int deleteByExample(RewardPurchaseRecordDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward_purchase_record
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward_purchase_record
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    int insert(RewardPurchaseRecordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward_purchase_record
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    int insertSelective(RewardPurchaseRecordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward_purchase_record
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    List<RewardPurchaseRecordDO> selectByExampleWithBLOBs(RewardPurchaseRecordDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward_purchase_record
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    List<RewardPurchaseRecordDO> selectByExample(RewardPurchaseRecordDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward_purchase_record
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    RewardPurchaseRecordDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward_purchase_record
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    int updateByExampleSelective(@Param("record") RewardPurchaseRecordDO record, @Param("example") RewardPurchaseRecordDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward_purchase_record
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    int updateByExampleWithBLOBs(@Param("record") RewardPurchaseRecordDO record, @Param("example") RewardPurchaseRecordDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward_purchase_record
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    int updateByExample(@Param("record") RewardPurchaseRecordDO record, @Param("example") RewardPurchaseRecordDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward_purchase_record
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    int updateByPrimaryKeySelective(RewardPurchaseRecordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward_purchase_record
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    int updateByPrimaryKeyWithBLOBs(RewardPurchaseRecordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward_purchase_record
     *
     * @mbg.generated Sat Feb 07 19:27:58 CST 2026
     */
    int updateByPrimaryKey(RewardPurchaseRecordDO record);
}