package com.star.reward.infrastructure.persistence.dao.mapper;

import com.star.reward.infrastructure.persistence.dao.entity.RewardTaskInstanceDO;
import com.star.reward.infrastructure.persistence.dao.entity.RewardTaskInstanceDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RewardTaskInstanceDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward_task_instance
     *
     * @mbg.generated Mon Jan 26 16:13:28 CST 2026
     */
    long countByExample(RewardTaskInstanceDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward_task_instance
     *
     * @mbg.generated Mon Jan 26 16:13:28 CST 2026
     */
    int deleteByExample(RewardTaskInstanceDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward_task_instance
     *
     * @mbg.generated Mon Jan 26 16:13:28 CST 2026
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward_task_instance
     *
     * @mbg.generated Mon Jan 26 16:13:28 CST 2026
     */
    int insert(RewardTaskInstanceDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward_task_instance
     *
     * @mbg.generated Mon Jan 26 16:13:28 CST 2026
     */
    int insertSelective(RewardTaskInstanceDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward_task_instance
     *
     * @mbg.generated Mon Jan 26 16:13:28 CST 2026
     */
    List<RewardTaskInstanceDO> selectByExampleWithBLOBs(RewardTaskInstanceDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward_task_instance
     *
     * @mbg.generated Mon Jan 26 16:13:28 CST 2026
     */
    List<RewardTaskInstanceDO> selectByExample(RewardTaskInstanceDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward_task_instance
     *
     * @mbg.generated Mon Jan 26 16:13:28 CST 2026
     */
    RewardTaskInstanceDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward_task_instance
     *
     * @mbg.generated Mon Jan 26 16:13:28 CST 2026
     */
    int updateByExampleSelective(@Param("row") RewardTaskInstanceDO row, @Param("example") RewardTaskInstanceDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward_task_instance
     *
     * @mbg.generated Mon Jan 26 16:13:28 CST 2026
     */
    int updateByExampleWithBLOBs(@Param("row") RewardTaskInstanceDO row, @Param("example") RewardTaskInstanceDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward_task_instance
     *
     * @mbg.generated Mon Jan 26 16:13:28 CST 2026
     */
    int updateByExample(@Param("row") RewardTaskInstanceDO row, @Param("example") RewardTaskInstanceDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward_task_instance
     *
     * @mbg.generated Mon Jan 26 16:13:28 CST 2026
     */
    int updateByPrimaryKeySelective(RewardTaskInstanceDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward_task_instance
     *
     * @mbg.generated Mon Jan 26 16:13:28 CST 2026
     */
    int updateByPrimaryKeyWithBLOBs(RewardTaskInstanceDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward_task_instance
     *
     * @mbg.generated Mon Jan 26 16:13:28 CST 2026
     */
    int updateByPrimaryKey(RewardTaskInstanceDO row);
}